/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Client facade for registered inference endpoints. */
export declare class SippClient {
  constructor(options?: SippClientOptions)
  readonly models: ModelStore
  /** Register or replace a local, gateway, or direct provider endpoint. */
  add(id: string, endpoint: Endpoint): Promise<EndpointRef>
  /** Remove a registered endpoint. */
  remove(id: string): Promise<void>
  /** Start raw-prompt text generation and return the run handle. */
  query(input: QueryInput, options?: QueryOptions): SippTextRun
  /** Start chat generation from ordered role/content messages. */
  chat(input: ChatInput, options?: QueryOptions): SippTextRun
  /** Start a single-input embedding request. */
  embed(input: string, options?: EmbedOptions): SippEmbeddingRun
  /** Start speech recognition from encoded WAV, MP3, or FLAC audio. */
  listen(audio: Buffer, options?: ListenOptions): SippTextRun
  /** Start speech synthesis and return a WAV response. */
  speak(text: string, options?: SpeakOptions): SippAudioRun
}

/** Client storage configuration. */
export interface SippClientOptions {
  readonly storageRoot?: string
}

/** Model managed by a client model store. */
export interface ManagedModel {
  readonly id: string
  readonly name: string
  readonly bytes: number
  readonly modality: string
  readonly status: string
}

/** Models available to a Sipp client. */
export declare class ModelStore {
  /** Add a model from local paths or HTTP(S) URLs. */
  add(sources: readonly string[]): Promise<ManagedModel>
  /** List available models. */
  list(): Promise<ManagedModel[]>
  /** Remove a model that is not used by an endpoint. */
  remove(modelId: string): Promise<void>
}

/** Text generation handle with a final response and optional token stream. */
export declare class SippTextRun {
  readonly response: Promise<SippTextResponse>
  readonly tokens: AsyncIterable<TokenBatch>
  cancel(reason?: CancellationReason): void
  [Symbol.asyncIterator](): AsyncIterator<TokenBatch>
}

/** Embedding request handle with a final embedding response. */
export declare class SippEmbeddingRun {
  readonly response: Promise<SippEmbeddingResponse>
  cancel(reason?: CancellationReason): void
}

/** Speech-synthesis handle with a final WAV response. */
export declare class SippAudioRun {
  readonly response: Promise<SippAudioResponse>
  cancel(reason?: CancellationReason): void
}

/** Reason propagated when an in-flight inference request is cancelled. */
export type CancellationReason =
  | 'caller_cancelled'
  | 'client_disconnected'
  | 'server_shutdown'
  | 'deadline_exceeded'

/** Return JSON backend/device observability reported by the native runtime. */
export declare function backendObservabilityJson(includeDetails?: boolean | undefined | null): string

/** Prefix KV-cache reuse and snapshot settings for local inference. */
export interface CacheRuntimeConfig {
  mode?: string
  retained_prefix_tokens?: number
  snapshot_interval_tokens?: number
  max_snapshot_entries?: number
  max_snapshot_bytes?: number
}

/** Chat message accepted by chat requests. */
export interface ChatMessage {
  role: string
  content: string
}

declare const endpointRefBrand: unique symbol

/** Opaque reference returned by endpoint registration. */
export type EndpointRef = { readonly [endpointRefBrand]: true }

/** Raw prompt accepted by positional query calls. */
export type QueryInput = string | {
  readonly prompt: string
  readonly media?: readonly Buffer[]
}

/** Ordered messages accepted by positional chat calls. */
export type ChatInput = readonly ChatMessage[] | {
  readonly messages: readonly ChatMessage[]
  readonly media?: readonly Buffer[]
}

/** Options shared by positional query and chat calls. */
export interface QueryOptions {
  readonly endpoint?: EndpointRef
  readonly contextKey?: string
  readonly maxTokens?: number
  readonly temperature?: number
  readonly topP?: number
  readonly sampling?: SamplingRuntimeOverride
  readonly stop?: readonly string[]
  readonly emitTokens?: boolean
  readonly grammar?: string
  readonly extra?: Record<string, unknown>
}

/** Options for a positional embedding call. */
export interface EmbedOptions {
  readonly endpoint?: EndpointRef
  readonly normalize?: boolean
  readonly contextKey?: string
  readonly extra?: Record<string, unknown>
}

/** Options for a positional speech-recognition call. */
export interface ListenOptions {
  readonly endpoint?: EndpointRef
  readonly language?: string
  readonly maxTokens?: number
}

/** Options for a positional speech-synthesis call. */
export interface SpeakOptions {
  readonly endpoint?: EndpointRef
  readonly language?: string
  readonly speakerAudio?: Buffer
  readonly maxDurationMs?: number
}

/** Token accounting returned by an inference endpoint. */
export interface TokenUsage {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
}

/** Final text response from query or chat generation. */
export interface SippTextResponse {
  endpoint: EndpointRef
  text: string
  finishReason: string
  usage?: TokenUsage
  localStats?: RequestStats
  metadata: SippResponseMetadata
}

/** Final embedding response from an embedding request. */
export interface SippEmbeddingResponse {
  endpoint: EndpointRef
  values: Array<number>
  usage?: TokenUsage
  localStats?: RequestStats
  pooling?: PoolingType
  normalized?: boolean
  metadata: SippResponseMetadata
}

/** Final mono PCM16 WAV response from speech synthesis. */
export interface SippAudioResponse {
  endpoint: EndpointRef
  audio: Buffer
  sampleRateHz: number
  channels: number
  durationMs: number
  metadata: SippResponseMetadata
}

/** Protocol correlation identifiers attached to an inference response. */
export interface SippResponseMetadata {
  requestId?: string
  upstreamRequestId?: string
  upstreamResponseId?: string
}

/** llama.cpp context, threading, attention, and embedding settings. */
export interface ContextRuntimeConfig {
  n_ctx?: number
  n_batch?: number
  n_ubatch?: number
  n_parallel?: number
  n_threads?: number
  n_threads_batch?: number
  flash_attention?: string
  kv_unified?: boolean
  cache_type_k?: string
  cache_type_v?: string
  offload_kqv?: boolean
  op_offload?: boolean
  swa_full?: boolean
  warmup?: boolean
  rope_scaling?: string
  rope_freq_base?: number
  rope_freq_scale?: number
  yarn_orig_ctx?: number
  yarn_ext_factor?: number
  yarn_attn_factor?: number
  yarn_beta_fast?: number
  yarn_beta_slow?: number
  embeddings?: boolean
  pooling?: PoolingType
}

/** Explicit GPU layer count for model placement. */
export interface GpuLayerCountConfig {
  count: number
}

/** Per-token logit bias applied during sampling. */
export interface LogitBiasConfig {
  token: number
  bias: number
}

/** Device placement and memory-mapping settings for local model loading. */
export interface ModelPlacementConfig {
  devices?: Array<string>
  gpu_layers?: string | GpuLayerCountConfig
  split_mode?: string
  main_gpu?: number
  tensor_split?: Array<number>
  use_mmap?: boolean
  use_mlock?: boolean
  fit_params?: boolean
  fit_params_min_ctx?: number
  fit_params_target_bytes?: Array<number>
  check_tensors?: boolean
  no_extra_bufts?: boolean
  no_host?: boolean
}

/** Vision projector and image-token settings for multimodal models. */
export interface MultimodalRuntimeConfig {
  projector_path?: string
  use_gpu?: boolean
  image_min_tokens?: number
  image_max_tokens?: number
}

/** Complete local native runtime configuration. */
export interface NativeRuntimeConfig {
  placement?: ModelPlacementConfig
  context?: ContextRuntimeConfig
  sampling?: SamplingRuntimeConfig
  scheduler?: SchedulerRuntimeConfig
  cache?: CacheRuntimeConfig
  multimodal?: MultimodalRuntimeConfig
  residency?: ResidencyRuntimeConfig
  observability?: ObservabilityRuntimeConfig
}

/** Local runtime metrics and backend profiling options. */
export interface ObservabilityRuntimeConfig {
  runtime_metrics?: boolean
  backend_profiling?: boolean
}

/** Embedding pooling strategy reported by or requested from the runtime. */
export declare const enum PoolingType {
  Unspecified = 'unspecified',
  None = 'none',
  Mean = 'mean',
  Cls = 'cls',
  Last = 'last',
  Rank = 'rank'
}

/** Authentication strategy used by a gateway endpoint. */
export interface GatewayAuthentication {
  readonly kind: 'none' | 'bearer' | 'header'
  readonly value?: string
  readonly headerName?: string
}

/** Options for a client-owned HTTP gateway endpoint. */
export interface GatewayEndpointOptions {
  readonly target: string
  readonly baseUrl: string
  readonly authentication?: GatewayAuthentication
  readonly staticHeaders?: readonly ProviderStaticHeader[]
  readonly timeoutMs?: number
  readonly queryRoute?: string
  readonly chatRoute?: string
  readonly embedRoute?: string
  readonly protocolOptions?: Readonly<Record<string, unknown>>
}

/** Static HTTP header attached to every request for a provider or gateway endpoint. */
export interface ProviderStaticHeader {
  readonly name: string
  readonly value: string
}

/** Options for a local model endpoint. */
export interface LocalEndpointOptions {
  readonly runtime?: NativeRuntimeConfig
}

/** Options for an explicitly selected external provider adapter. */
export interface ProviderEndpointOptions {
  readonly provider: 'openai' | 'anthropic' | 'openai_compatible'
  readonly model: string
  readonly apiKey?: string
  readonly baseUrl?: string
  readonly timeoutMs?: number
  readonly version?: string
  readonly authHeaderName?: string
  readonly authHeaderValue?: string
  readonly staticHeaders?: readonly ProviderStaticHeader[]
  readonly correlationHeader?: string
}

/** Unregistered endpoint configuration accepted by the client. */
export declare class Endpoint {
  private constructor()
  static local(model: ManagedModel, options?: LocalEndpointOptions): Endpoint
  static gateway(options: GatewayEndpointOptions): Endpoint
  static provider(options: ProviderEndpointOptions): Endpoint
}

/** Error raised when native model acquisition or lifecycle processing fails. */
export interface ModelLifecycleError extends Error {
  readonly code: string
  readonly status?: number
  readonly retryAfterMs?: number
}

/** Local runtime timing, cache, and throughput statistics. */
export interface RequestStats {
  inputTokens: number
  outputTokens: number
  cacheMode: string
  cacheSource: string
  cacheHits: number
  prefillTokens: number
  ttftMs?: number
  interTokenMs?: number
  e2eMs?: number
  e2eTokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
}

/** GPU residency limits for concurrently loaded local models. */
export interface ResidencyRuntimeConfig {
  max_gpu_models_per_device?: number
  allow_cpu_models_while_gpu_loaded?: boolean
  require_gpu_lease?: boolean
  gpu_memory_safety_margin_bytes?: number
}

/** Sampling controls passed to llama.cpp for local generation. */
export interface SamplingRuntimeConfig {
  samplers?: Array<string>
  seed?: number
  top_k?: number
  top_p?: number
  min_p?: number
  typical_p?: number
  xtc_probability?: number
  xtc_threshold?: number
  top_n_sigma?: number
  temperature?: number
  dynatemp_range?: number
  dynatemp_exponent?: number
  repeat_last_n?: number
  repeat_penalty?: number
  frequency_penalty?: number
  presence_penalty?: number
  dry_multiplier?: number
  dry_base?: number
  dry_allowed_length?: number
  dry_penalty_last_n?: number
  dry_sequence_breakers?: Array<string>
  mirostat?: number
  mirostat_tau?: number
  mirostat_eta?: number
  min_keep?: number
  n_probs?: number
  logit_bias?: Array<LogitBiasConfig>
  ignore_eos?: boolean
  grammar_lazy?: boolean
  preserved_tokens?: Array<number>
  backend_sampling?: boolean
}

/** Request-level local sampler override applied over runtime defaults. */
export type SamplingRuntimeOverride = SamplingRuntimeConfig

/** Scheduler policy knobs for latency, balance, or throughput behavior. */
export interface SchedulerPolicyConfig {
  mode?: string
  decode_token_reserve?: number
  enable_adaptive_prefill_chunking?: boolean
}

/** Request scheduler and continuous batching settings. */
export interface SchedulerRuntimeConfig {
  continuous_batching?: boolean
  policy?: SchedulerPolicyConfig
  prefill_chunk_size?: number
  max_running_requests?: number
  max_queued_requests?: number
}

/** Enable or suppress llama.cpp native logging. */
export declare function setLlamaLogQuiet(quiet: boolean): void

/** Counters describing token batch emission through the native bridge. */
export interface TokenEmissionStats {
  framesSent: number
  bytesSent: number
  batchesSent: number
}

/** Incremental text emitted by a running generation request. */
export interface TokenBatch {
  requestId: string
  streamId: number
  sequenceStart: number
  text: string
  frameCount: number
  byteCount: number
  stats: TokenEmissionStats
}
