/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Client facade for local CogentLM models and remote gateway aliases. */
export declare class CogentClient {
  constructor()
  /** Register or replace a local model, remote gateway, or direct provider endpoint. */
  add(id: string, descriptor: EndpointDescriptor): Promise<EndpointRef>
  /** Start raw-prompt text generation and return the run handle. */
  query(request: CogentQueryRequest): CogentTextRun
  /** Start chat generation from ordered role/content messages. */
  chat(request: CogentChatRequest): CogentTextRun
  /** Start a single-input embedding request. */
  embed(request: CogentEmbedRequest): CogentEmbeddingRun
}

/** Text generation handle with a final response and optional token stream. */
export declare class CogentTextRun {
  readonly response: Promise<CogentTextResponse>
  readonly tokens: AsyncIterable<TokenBatch>
  cancel(reason?: CancellationReason): void
  [Symbol.asyncIterator](): AsyncIterator<TokenBatch>
}

/** Embedding request handle with a final embedding response. */
export declare class CogentEmbeddingRun {
  readonly response: Promise<CogentEmbeddingResponse>
  cancel(reason?: CancellationReason): void
}

export type CancellationReason =
  | 'caller_cancelled'
  | 'client_disconnected'
  | 'server_shutdown'
  | 'deadline_exceeded'

/** Return JSON backend/device observability reported by the native runtime. */
export declare function backendObservabilityJson(includeDetails?: boolean | undefined | null): string

/** Prefix KV-cache reuse and snapshot settings for local inference. */
export interface CacheRuntimeConfig {
  mode?: string
  retained_prefix_tokens?: number
  snapshot_interval_tokens?: number
  max_snapshot_entries?: number
  max_snapshot_bytes?: number
}

/** Chat message accepted by local and remote chat requests. */
export interface ChatMessage {
  role: string
  content: string
}

/** Address of a local model or remote gateway endpoint registered in a client. */
export type EndpointRef =
  | {
      kind: 'local'
      id: string
    }
  | {
      kind: 'remote'
      id: string
    }
  | {
      kind: 'provider'
      id: string
    }

/** Shared generation options for text-producing requests. */
export interface CogentTextOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  stop?: Array<string>
}

/** Local-only prompt options such as grammar constraints and image inputs. */
export interface LocalTextOptions {
  contextKey?: string
  grammar?: string
  jsonSchema?: string
  sampling?: SamplingRuntimeConfig
  media?: Array<Buffer>
}

/** Local-only embedding options for context and vector normalization. */
export interface LocalEmbedOptions {
  contextKey?: string
  normalize?: boolean
}

/** Raw-prompt text generation request. */
export interface CogentQueryRequest {
  requestId?: string
  endpoint?: EndpointRef
  prompt: string
  options?: CogentTextOptions
  local?: LocalTextOptions
  gatewayOptions?: Record<string, unknown>
  providerOptions?: Record<string, unknown>
  emitTokens?: boolean
}

/** Chat text generation request. */
export interface CogentChatRequest {
  requestId?: string
  endpoint?: EndpointRef
  messages: Array<ChatMessage>
  options?: CogentTextOptions
  local?: LocalTextOptions
  gatewayOptions?: Record<string, unknown>
  providerOptions?: Record<string, unknown>
  emitTokens?: boolean
}

/** Single-input embedding request. */
export interface CogentEmbedRequest {
  requestId?: string
  endpoint?: EndpointRef
  input: string
  local?: LocalEmbedOptions
  gatewayOptions?: Record<string, unknown>
  providerOptions?: Record<string, unknown>
}

/** Token accounting returned by a local or remote request. */
export interface TokenUsage {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
}

/** Final text response from query or chat generation. */
export interface CogentTextResponse {
  endpoint: EndpointRef
  text: string
  finishReason: string
  usage?: TokenUsage
  localStats?: RequestStats
  metadata: CogentResponseMetadata
}

/** Final embedding response from an embedding request. */
export interface CogentEmbeddingResponse {
  endpoint: EndpointRef
  values: Array<number>
  usage?: TokenUsage
  localStats?: RequestStats
  pooling?: PoolingType
  normalized?: boolean
  metadata: CogentResponseMetadata
}

export interface CogentResponseMetadata {
  requestId?: string
  upstreamRequestId?: string
  upstreamResponseId?: string
}

/** llama.cpp context, threading, attention, and embedding settings. */
export interface ContextRuntimeConfig {
  n_ctx?: number
  n_batch?: number
  n_ubatch?: number
  n_parallel?: number
  n_threads?: number
  n_threads_batch?: number
  flash_attention?: string
  kv_unified?: boolean
  cache_type_k?: string
  cache_type_v?: string
  offload_kqv?: boolean
  op_offload?: boolean
  swa_full?: boolean
  warmup?: boolean
  rope_scaling?: string
  rope_freq_base?: number
  rope_freq_scale?: number
  yarn_orig_ctx?: number
  yarn_ext_factor?: number
  yarn_attn_factor?: number
  yarn_beta_fast?: number
  yarn_beta_slow?: number
  embeddings?: boolean
  pooling?: PoolingType
}

/** Explicit GPU layer count for model placement. */
export interface GpuLayerCountConfig {
  count: number
}

/** Per-token logit bias applied during sampling. */
export interface LogitBiasConfig {
  token: number
  bias: number
}

/** Device placement and memory-mapping settings for local model loading. */
export interface ModelPlacementConfig {
  devices?: Array<string>
  gpu_layers?: string | GpuLayerCountConfig
  split_mode?: string
  main_gpu?: number
  tensor_split?: Array<number>
  use_mmap?: boolean
  use_mlock?: boolean
  fit_params?: boolean
  fit_params_min_ctx?: number
  fit_params_target_bytes?: Array<number>
  check_tensors?: boolean
  no_extra_bufts?: boolean
  no_host?: boolean
}

/** Vision projector and image-token settings for multimodal models. */
export interface MultimodalRuntimeConfig {
  projector_path?: string
  use_gpu?: boolean
  image_min_tokens?: number
  image_max_tokens?: number
}

/** Complete local native runtime configuration. */
export interface NativeRuntimeConfig {
  placement?: ModelPlacementConfig
  context?: ContextRuntimeConfig
  sampling?: SamplingRuntimeConfig
  scheduler?: SchedulerRuntimeConfig
  cache?: CacheRuntimeConfig
  multimodal?: MultimodalRuntimeConfig
  residency?: ResidencyRuntimeConfig
  observability?: ObservabilityRuntimeConfig
}

/** Local runtime metrics and backend profiling options. */
export interface ObservabilityRuntimeConfig {
  runtime_metrics?: boolean
  backend_profiling?: boolean
}

/** Embedding pooling strategy reported by or requested from the runtime. */
export declare const enum PoolingType {
  Unspecified = 'unspecified',
  None = 'none',
  Mean = 'mean',
  Cls = 'cls',
  Last = 'last',
  Rank = 'rank'
}

/** Remote CogentLM gateway alias, URL, token, and optional timeout. */
export interface RemoteGatewayConfig {
  readonly alias: string
  readonly baseUrl: string
  readonly token: string
  readonly timeoutMs?: number
}

export interface ProviderStaticHeader {
  name: string
  value: string
}

export type LocalEndpointDescriptor = {
  kind: 'local'
  modelPath: string
  config?: NativeRuntimeConfig
}

export type GatewayEndpointDescriptor = {
  kind: 'gateway' | 'remote'
  alias: string
  baseUrl: string
  token: string
  timeoutMs?: number
}

export type ProviderEndpointDescriptor = {
  kind: 'provider'
  provider: 'openai' | 'anthropic' | 'openai_compatible' | 'openai-compatible'
  model: string
  apiKey?: string
  baseUrl?: string
  timeoutMs?: number
  version?: string
  authHeaderName?: string
  authHeaderValue?: string
  staticHeaders?: Array<ProviderStaticHeader>
  correlationHeader?: string
}

export type EndpointDescriptor =
  | LocalEndpointDescriptor
  | GatewayEndpointDescriptor
  | ProviderEndpointDescriptor

/** Local runtime timing, cache, and throughput statistics. */
export interface RequestStats {
  inputTokens: number
  outputTokens: number
  cacheMode: string
  cacheSource: string
  cacheHits: number
  prefillTokens: number
  ttftMs?: number
  interTokenMs?: number
  e2eMs?: number
  e2eTokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
}

/** GPU residency limits for concurrently loaded local models. */
export interface ResidencyRuntimeConfig {
  max_gpu_models_per_device?: number
  allow_cpu_models_while_gpu_loaded?: boolean
  require_gpu_lease?: boolean
  gpu_memory_safety_margin_bytes?: number
}

/** Sampling controls passed to llama.cpp for local generation. */
export interface SamplingRuntimeConfig {
  samplers?: Array<string>
  seed?: number
  top_k?: number
  top_p?: number
  min_p?: number
  typical_p?: number
  xtc_probability?: number
  xtc_threshold?: number
  top_n_sigma?: number
  temperature?: number
  dynatemp_range?: number
  dynatemp_exponent?: number
  repeat_last_n?: number
  repeat_penalty?: number
  frequency_penalty?: number
  presence_penalty?: number
  dry_multiplier?: number
  dry_base?: number
  dry_allowed_length?: number
  dry_penalty_last_n?: number
  dry_sequence_breakers?: Array<string>
  mirostat?: number
  mirostat_tau?: number
  mirostat_eta?: number
  min_keep?: number
  n_probs?: number
  logit_bias?: Array<LogitBiasConfig>
  ignore_eos?: boolean
  grammar_lazy?: boolean
  preserved_tokens?: Array<number>
  backend_sampling?: boolean
}

/** Scheduler policy knobs for latency, balance, or throughput behavior. */
export interface SchedulerPolicyConfig {
  mode?: string
  decode_token_reserve?: number
  enable_adaptive_prefill_chunking?: boolean
}

/** Request scheduler and continuous batching settings. */
export interface SchedulerRuntimeConfig {
  continuous_batching?: boolean
  policy?: SchedulerPolicyConfig
  prefill_chunk_size?: number
  max_running_requests?: number
  max_queued_requests?: number
}

/** Enable or suppress llama.cpp native logging. */
export declare function setLlamaLogQuiet(quiet: boolean): void

/** Counters describing token batch emission through the native bridge. */
export interface TokenEmissionStats {
  framesSent: number
  bytesSent: number
  batchesSent: number
}

/** Incremental text emitted by a running generation request. */
export interface TokenBatch {
  requestId: string
  streamId: number
  sequenceStart: number
  text: string
  frameCount: number
  byteCount: number
  stats: TokenEmissionStats
}
