[book]
authors = ["Noumena Labs"]
language = "en"
src = "docs"
title = "Sipp Documentation"

[build]
build-dir = "book"

[preprocessor.mermaid]

[output.html]
additional-css = ["theme/sipp.css"]
additional-js = ["docs/assets/language-switch.js", "theme/mermaid-init.js"]
edit-url-template = "https://github.com/noumena-labs/Sipp/edit/master/{path}"
git-repository-url = "https://github.com/noumena-labs/Sipp"
site-url = "/Sipp/"

[output.html.search]
enable = true
