/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CogentEngine {
  static load(modelPath: string, config?: NativeRuntimeConfig | undefined | null): Promise<unknown>
  get closed(): boolean
  query(prompt: string, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<unknown>
  queryResponse(prompt: string, options?: QueryOptions | undefined | null): Promise<unknown>
  queryResult(prompt: string, options?: QueryOptions | undefined | null): Promise<unknown>
  chat(messages: Array<ChatMessage>, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<unknown>
  chatResponse(messages: Array<ChatMessage>, options?: QueryOptions | undefined | null): Promise<unknown>
  chatResult(messages: Array<ChatMessage>, options?: QueryOptions | undefined | null): Promise<unknown>
  close(): Promise<unknown>
  state(): Promise<unknown>
  drainEvents(): Array<EngineEvent>
}

export declare class ModelService {
  constructor(storePath: string)
  get closed(): boolean
  loadPath(modelPath: string, options?: ModelLoadOptions | undefined | null): Promise<unknown>
  loadVision(modelPath: string, projectorPath: string, options?: ModelLoadOptions | undefined | null): Promise<unknown>
  loadInstalled(modelId: string, options?: ModelLoadOptions | undefined | null): Promise<unknown>
  unload(): Promise<unknown>
  remove(modelId: string): Promise<unknown>
  list(): Array<ManagedModelInfo>
  current(): ManagedModelInfo | null
  query(prompt: string, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<unknown>
  chat(messages: Array<ChatMessage>, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<unknown>
  state(): Promise<unknown>
  close(): Promise<unknown>
  drainEvents(): Array<EngineEvent>
}

export interface BackendDevice {
  id?: string
  name: string
  type: string
  memoryTotalBytes?: number
  memoryFreeBytes?: number
}

export interface BackendInfo {
  selected: string
  available: Array<string>
  devices: Array<BackendDevice>
}

export declare function backendObservabilityJson(includeDetails?: boolean | undefined | null): string

export interface BackendSelection {
  requested: string
  selected: string
  available: Array<string>
  gpuOffloadExpected: boolean
  reason?: string
}

export interface CacheRuntimeConfig {
  mode?: string
  retainedPrefixTokens?: number
  snapshotIntervalTokens?: number
  maxSnapshotEntries?: number
  maxSnapshotBytes?: number
  maxSessionEntries?: number
  cacheKeyPolicy?: string
  enableContextCheckpoints?: boolean
  checkpointEveryTokens?: number
}

export interface ChatMessage {
  role: string
  content: string
}

export interface ContextRuntimeConfig {
  nCtx?: number
  nBatch?: number
  nUbatch?: number
  nParallel?: number
  nThreads?: number
  nThreadsBatch?: number
  flashAttention?: string
  kvUnified?: boolean
  cacheTypeK?: string
  cacheTypeV?: string
  offloadKqv?: boolean
  opOffload?: boolean
  swaFull?: boolean
  warmup?: boolean
  ropeScaling?: string
  ropeFreqBase?: number
  ropeFreqScale?: number
  yarnOrigCtx?: number
  yarnExtFactor?: number
  yarnAttnFactor?: number
  yarnBetaFast?: number
  yarnBetaSlow?: number
}

export interface EngineEvent {
  type: string
  state?: EngineState
  loadedBytes?: number
  totalBytes?: number
  assetName?: string
  requestId?: string
  streamId?: number
  result?: RequestResult
  error?: string
}

export interface EngineState {
  status: string
  model?: ModelState
  backend: BackendInfo
  runtime?: ResolvedRuntimeLimits
  requests: Array<RequestState>
  stats: EngineStats
  updatedAtUnixMs: number
}

export interface EngineStats {
  requestsRunning: number
  requestsQueued: number
  requestsCompleted: number
  requestsFailed: number
  inputTokens: number
  outputTokens: number
  cacheHits: number
  prefillTokens: number
  ttftMs?: number
  interTokenMs?: number
  e2EMs?: number
  tokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
  backendMs: number
  syncMs: number
  engineOverheadMs: number
  debugMetricsSchedulerTicks: number
  debugMetricsDecodeTicks: number
  debugMetricsPrefillTicks: number
  debugMetricsBackendSamplerAttachAttempts: number
  debugMetricsBackendSamplerAttachFailures: number
  debugMetricsAdmitMs: number
  debugMetricsNormalizeMs: number
  debugMetricsBackendSamplerAttachMs: number
  debugMetricsSelectSlotsMs: number
  debugMetricsPlanMs: number
  debugMetricsBatchBuildMs: number
  debugMetricsLlamaDecodeMs: number
  debugMetricsLlamaSyncMs: number
  debugMetricsApplyBookkeepingMs: number
  debugMetricsApplyDecodeResultsMs: number
  debugMetricsSampleMs: number
  debugMetricsTokenPieceMs: number
  debugMetricsEmitMs: number
  debugMetricsPrefixQueueMs: number
  debugMetricsFinalizeMs: number
  debugMetricsCommitObservabilityMs: number
  debugMetricsPostDecodeMs: number
}

export interface GenerationResponse {
  requestId: number
  status: string
  completed: boolean
  failed: boolean
  cancelled: boolean
  outputText: string
  errorMessage?: string
  observability: RequestObservabilityMetrics
}

export interface LoadedModelInfo {
  model: ManagedModelInfo
  backend: BackendSelection
  runtimeFingerprint: string
}

export interface LogitBiasConfig {
  token: number
  bias: number
}

export interface ManagedModelInfo {
  id: string
  name: string
  modality: string
  status: string
  source: string
  bytes: number
  loaded: boolean
  chatTemplate?: string
  bosText: string
  eosText: string
  mediaMarker?: string
  createdAtUnixMs: number
  updatedAtUnixMs: number
}

export interface ModelLoadOptions {
  backend?: string
  stats?: string
  runtime?: NativeRuntimeConfig
}

export interface ModelPlacementConfig {
  devices?: Array<string>
  gpuLayers?: string
  splitMode?: string
  mainGpu?: number
  tensorSplit?: Array<number>
  useMmap?: boolean
  useMlock?: boolean
  fitParams?: boolean
  fitParamsMinCtx?: number
  fitParamsTargetBytes?: Array<number>
  checkTensors?: boolean
  noExtraBufts?: boolean
  noHost?: boolean
}

export interface ModelServiceState {
  status: string
  model?: ManagedModelInfo
  backend: BackendInfo
  runtime?: ResolvedRuntimeLimits
  requests: Array<RequestState>
  stats: EngineStats
  updatedAtUnixMs: number
}

export interface ModelState {
  id: string
  name: string
}

export interface MultimodalRuntimeConfig {
  projectorPath?: string
  useGpu?: boolean
  imageMinTokens?: number
  imageMaxTokens?: number
}

export interface NativeRuntimeConfig {
  placement?: ModelPlacementConfig
  context?: ContextRuntimeConfig
  sampling?: SamplingRuntimeConfig
  scheduler?: SchedulerRuntimeConfig
  cache?: CacheRuntimeConfig
  multimodal?: MultimodalRuntimeConfig
  residency?: ResidencyRuntimeConfig
  observability?: ObservabilityRuntimeConfig
}

export interface ObservabilityRuntimeConfig {
  runtimeMetrics?: boolean
  backendProfiling?: boolean
}

export interface QueryOptions {
  contextKey?: string
  maxTokens?: number
  grammar?: string
  jsonSchema?: string
  stop?: Array<string>
  sampling?: SamplingRuntimeConfig
  media?: Array<Buffer>
}

export interface RequestObservabilityMetrics {
  ttftMs: number
  itlAvgMs: number
  itlP99Ms: number
  e2EMs: number
  prefillMs: number
  decodeMs: number
  nativeGpuMs: number
  nativeSyncMs: number
  nativeLogicMs: number
  inputTokens: number
  outputTokens: number
  cacheHits: number
  prefillTokens: number
}

export interface RequestResult {
  id: string
  text: string
  finishReason: string
  stats: RequestStats
}

export interface RequestState {
  id: string
  status: string
  inputTokens: number
  outputTokens: number
}

export interface RequestStats {
  inputTokens: number
  outputTokens: number
  cacheHits: number
  ttftMs?: number
  interTokenMs?: number
  e2EMs?: number
  tokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
  debugMetricsSchedulerTicks: number
  debugMetricsDecodeTicks: number
  debugMetricsPrefillTicks: number
  debugMetricsBackendSamplerAttachAttempts: number
  debugMetricsBackendSamplerAttachFailures: number
  debugMetricsAdmitMs: number
  debugMetricsNormalizeMs: number
  debugMetricsBackendSamplerAttachMs: number
  debugMetricsSelectSlotsMs: number
  debugMetricsPlanMs: number
  debugMetricsBatchBuildMs: number
  debugMetricsLlamaDecodeMs: number
  debugMetricsLlamaSyncMs: number
  debugMetricsApplyBookkeepingMs: number
  debugMetricsApplyDecodeResultsMs: number
  debugMetricsSampleMs: number
  debugMetricsTokenPieceMs: number
  debugMetricsEmitMs: number
  debugMetricsPrefixQueueMs: number
  debugMetricsFinalizeMs: number
  debugMetricsCommitObservabilityMs: number
  debugMetricsPostDecodeMs: number
}

export interface ResidencyRuntimeConfig {
  maxGpuModelsPerDevice?: number
  allowCpuModelsWhileGpuLoaded?: boolean
  requireGpuLease?: boolean
  gpuMemorySafetyMarginBytes?: number
}

export interface ResolvedRuntimeLimits {
  nCtx: number
  nBatch: number
  nUbatch: number
  nParallel: number
  kvUnified: boolean
  flashAttention: string
  cacheTypeK: string
  cacheTypeV: string
}

export interface SamplingRuntimeConfig {
  samplers?: Array<string>
  seed?: number
  topK?: number
  topP?: number
  minP?: number
  typicalP?: number
  xtcProbability?: number
  xtcThreshold?: number
  topNSigma?: number
  temperature?: number
  dynatempRange?: number
  dynatempExponent?: number
  repeatLastN?: number
  repeatPenalty?: number
  frequencyPenalty?: number
  presencePenalty?: number
  dryMultiplier?: number
  dryBase?: number
  dryAllowedLength?: number
  dryPenaltyLastN?: number
  drySequenceBreakers?: Array<string>
  mirostat?: number
  mirostatTau?: number
  mirostatEta?: number
  minKeep?: number
  nProbs?: number
  logitBias?: Array<LogitBiasConfig>
  ignoreEos?: boolean
  grammarLazy?: boolean
  preservedTokens?: Array<number>
  backendSampling?: boolean
}

export interface SchedulerRuntimeConfig {
  continuousBatching?: boolean
  policy?: string
  decodeTokenReserve?: number
  adaptivePrefillChunking?: boolean
  prefillChunkSize?: number
  maxRunningRequests?: number
  maxQueuedRequests?: number
}

export declare function setLlamaLogQuiet(quiet: boolean): void

export interface StreamStats {
  framesSent: number
  bytesSent: number
  framesDropped: number
  batchesSent: number
}

export interface TokenBatch {
  requestId: string
  streamId: number
  sequenceStart: number
  text: string
  frameCount: number
  byteCount: number
  stats: StreamStats
}
