pub use cogentlm_core::{StreamStats, TokenBatch};

/// Token streaming policy requested by a caller.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TokenStreamMode {
    #[default]
    Off,
    BestEffort,
    Lossless,
}

/// One generated byte span for one request stream.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TokenFrame {
    pub stream_id: u32,
    pub sequence: u32,
    pub flags: u32,
    pub bytes: Vec<u8>,
}
