//////////////////////////////////////////////////////////////////////////////
//
// character-config.ts
//
// - Types and loaders for `character.json`, the user-facing config that
//   ties a persona, action schema, and asset paths together.
//
// - The file format is intentionally small and self-documenting so it can
//   be hand-edited or generated by tooling.
//
//////////////////////////////////////////////////////////////////////////////

import type { ActionSchema } from './action-schema.js';
import { validateActionSchema } from './action-schema.js';
import type {
  PersonaCurrentLifeSpec,
  PersonaDialogExample,
  PersonaPersonalitySpec,
  PersonaSpec,
} from './persona.js';

export interface CharacterAssets {
  /**
   * Path (or URL) to a .vrm avatar file. Relative paths are resolved by the
   * host app; the harness itself does not perform I/O.
   */
  readonly vrm?: string;
  /** Optional idle animation clip (.vrma or .glb). */
  readonly idleAnimation?: string;
  /** Optional portrait image URL used by chat panels. */
  readonly portrait?: string;
}

export interface CharacterMemoryConfig {
  /**
   * Maximum number of prior (user, assistant) turn pairs to retain in the
   * sliding window. Older turns are dropped.
   */
  readonly maxTurns?: number;
}

export interface CharacterConfig {
  /**
   * Stable identifier. Used as the engine prefix-cache context key so the
   * immutable system prompt stays resident across turns.
   */
  readonly id: string;
  readonly persona: PersonaSpec;
  readonly actions: ActionSchema;
  readonly assets?: CharacterAssets;
  readonly memory?: CharacterMemoryConfig;
}

export class CharacterConfigError extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'CharacterConfigError';
  }
}

const ID_RE = /^[A-Za-z0-9_\-]+$/;

function isStringArray(value: unknown): value is readonly string[] {
  return Array.isArray(value) && value.every((entry) => typeof entry === 'string');
}

function validateOptionalStringArray(
  owner: Record<string, unknown>,
  key: string,
  errorMessage: string
): void {
  const value = owner[key];
  if (value != null && !isStringArray(value)) {
    throw new CharacterConfigError(errorMessage);
  }
}

function trimOptionalString(value: unknown): string | undefined {
  if (typeof value !== 'string') {
    return undefined;
  }
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function trimOptionalStringArray(value: unknown): readonly string[] | undefined {
  if (!isStringArray(value)) {
    return undefined;
  }
  const trimmed = value.map((entry) => entry.trim()).filter((entry) => entry.length > 0);
  return trimmed.length > 0 ? trimmed : undefined;
}

/**
 * Parses and validates a CharacterConfig object (e.g. the result of
 * `JSON.parse(readFileSync('character.json'))`). Throws CharacterConfigError
 * with a human-readable message on any problem.
 */
export function parseCharacterConfig(raw: unknown): CharacterConfig {
  if (raw == null || typeof raw !== 'object') {
    throw new CharacterConfigError('Character config must be a JSON object.');
  }
  const source = raw as Record<string, unknown>;

  const id = source.id;
  if (typeof id !== 'string' || !ID_RE.test(id)) {
    throw new CharacterConfigError(
      'Character config `id` must be a non-empty identifier ([A-Za-z0-9_-]+).'
    );
  }

  const persona = source.persona;
  if (persona == null || typeof persona !== 'object') {
    throw new CharacterConfigError('Character config `persona` must be an object.');
  }
  const personaRec = persona as Record<string, unknown>;
  if (typeof personaRec.name !== 'string' || personaRec.name.trim().length === 0) {
    throw new CharacterConfigError('`persona.name` is required and must be a non-empty string.');
  }
  if (personaRec.currentLife != null && typeof personaRec.currentLife !== 'object') {
    throw new CharacterConfigError('`persona.currentLife` must be an object if present.');
  }
  if (personaRec.personality != null && typeof personaRec.personality !== 'object') {
    throw new CharacterConfigError('`persona.personality` must be an object if present.');
  }
  if (personaRec.currentLife != null) {
    const currentLifeRec = personaRec.currentLife as Record<string, unknown>;
    for (const key of ['description']) {
      const value = currentLifeRec[key];
      if (value != null && typeof value !== 'string') {
        throw new CharacterConfigError(`\`persona.currentLife.${key}\` must be a string if present.`);
      }
    }
  }

  if (personaRec.personality != null) {
    const personalityRec = personaRec.personality as Record<string, unknown>;
    validateOptionalStringArray(personalityRec, 'traits', '`persona.personality.traits` must be an array of strings if present.');
    for (const key of ['description']) {
      const value = personalityRec[key];
      if (value != null && typeof value !== 'string') {
        throw new CharacterConfigError(`\`persona.personality.${key}\` must be a string if present.`);
      }
    }
  }

  if (personaRec.role != null && typeof personaRec.role !== 'string') {
    throw new CharacterConfigError('`persona.role` must be a string if present.');
  }
  if (personaRec.summary != null && typeof personaRec.summary !== 'string') {
    throw new CharacterConfigError('`persona.summary` must be a string if present.');
  }
  if (personaRec.backstory != null && typeof personaRec.backstory !== 'string') {
    throw new CharacterConfigError('`persona.backstory` must be a string if present.');
  }

  if (personaRec.notes != null) {
    if (!isStringArray(personaRec.notes)) {
      throw new CharacterConfigError('`persona.notes` must be an array of strings if present.');
    }
  }
  if (personaRec.dialogExamples != null) {
    if (!Array.isArray(personaRec.dialogExamples)) {
      throw new CharacterConfigError('`persona.dialogExamples` must be an array if present.');
    }
    const invalidIndex = personaRec.dialogExamples.findIndex((example) => {
      if (example == null || typeof example !== 'object') {
        return true;
      }
      const rec = example as Record<string, unknown>;
      return (
        typeof rec.user !== 'string' ||
        rec.user.trim().length === 0 ||
        typeof rec.assistant !== 'string' ||
        rec.assistant.trim().length === 0
      );
    });
    if (invalidIndex >= 0) {
      throw new CharacterConfigError(
        '`persona.dialogExamples` entries must be objects with non-empty string `user` and `assistant` fields.'
      );
    }
  }

  const actions = source.actions;
  if (actions == null || typeof actions !== 'object') {
    throw new CharacterConfigError('Character config `actions` must be an object.');
  }
  const schemaError = validateActionSchema(actions as ActionSchema);
  if (schemaError != null) {
    throw new CharacterConfigError(`Invalid actions schema: ${schemaError}`);
  }

  const assets = source.assets;
  if (assets != null && typeof assets !== 'object') {
    throw new CharacterConfigError('`assets` must be an object if present.');
  }

  const memory = source.memory;
  if (memory != null && typeof memory !== 'object') {
    throw new CharacterConfigError('`memory` must be an object if present.');
  }
  if (memory != null) {
    const memoryRec = memory as Record<string, unknown>;
    if (memoryRec.maxTurns != null) {
      if (
        typeof memoryRec.maxTurns !== 'number' ||
        !Number.isFinite(memoryRec.maxTurns) ||
        memoryRec.maxTurns < 0 ||
        Math.floor(memoryRec.maxTurns) !== memoryRec.maxTurns
      ) {
        throw new CharacterConfigError('`memory.maxTurns` must be a non-negative integer.');
      }
    }
  }

  return {
    id,
    persona: {
      name: personaRec.name.trim(),
      summary: trimOptionalString(personaRec.summary),
      role: trimOptionalString(personaRec.role),
      currentLife:
        personaRec.currentLife == null
          ? undefined
          : {
              description: trimOptionalString((personaRec.currentLife as Record<string, unknown>).description),
            } satisfies PersonaCurrentLifeSpec,
      personality:
        personaRec.personality == null
          ? undefined
          : {
              traits: trimOptionalStringArray((personaRec.personality as Record<string, unknown>).traits),
              description: trimOptionalString((personaRec.personality as Record<string, unknown>).description),
            } satisfies PersonaPersonalitySpec,
      backstory: trimOptionalString(personaRec.backstory),
      notes: trimOptionalStringArray(personaRec.notes),
      dialogExamples:
        personaRec.dialogExamples == null
          ? undefined
          : (personaRec.dialogExamples as readonly PersonaDialogExample[]).map((example) => ({
              user: example.user.trim(),
              assistant: example.assistant.trim(),
            })),
    } satisfies PersonaSpec,
    actions: actions as ActionSchema,
    assets: (assets as CharacterAssets | undefined) ?? undefined,
    memory: (memory as CharacterMemoryConfig | undefined) ?? undefined,
  };
}

/**
 * Default memory window. Chosen to keep prompt size bounded while still
 * providing enough recency for conversational coherence.
 */
export const DEFAULT_MEMORY_MAX_TURNS = 8;

export function resolveMaxMemoryTurns(config: CharacterConfig): number {
  const configured = config.memory?.maxTurns;
  if (configured == null) {
    return DEFAULT_MEMORY_MAX_TURNS;
  }
  return configured;
}
