/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CogentEngine {
  static load(modelPath: string, config?: NativeRuntimeConfig | undefined | null): Promise<CogentEngine>
  query(prompt: string, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<GenerationResult>
  chat(messages: Array<ChatMessage>, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<GenerationResult>
  embed(request: EmbedRequest): Promise<EmbeddingResult>
  state(): Promise<EngineState>
  drainEvents(): Array<EngineEvent>
}

export declare class ModelService {
  constructor(storePath: string)
  loadPath(modelPath: string, options?: ModelLoadOptions | undefined | null): Promise<LoadedModelInfo>
  loadVision(modelPath: string, projectorPath: string, options?: ModelLoadOptions | undefined | null): Promise<LoadedModelInfo>
  unload(): Promise<void>
  remove(modelId: string): Promise<void>
  list(): Array<ManagedModelInfo>
  current(): ManagedModelInfo | null
  query(prompt: string, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<GenerationResult>
  chat(messages: Array<ChatMessage>, options?: QueryOptions | undefined | null, onTokens?: TokenBatchCallback | undefined | null): Promise<GenerationResult>
  embed(request: EmbedRequest): Promise<EmbeddingResult>
  state(): Promise<ModelServiceState>
  drainEvents(): Array<EngineEvent>
}

export declare class ProviderClient {
  static proxy(config: ProviderProxyConfig): ProviderClient
  static openai(config: ProviderOpenAiConfig): ProviderClient
  static anthropic(config: ProviderAnthropicConfig): ProviderClient
  kind(): string
  listModels(): Promise<ProviderModel[]>
  getModel(model: string): Promise<ProviderModel>
  chat(request: ProviderChatRequest): Promise<ProviderChatResponse>
  generate(request: ProviderGenerateRequest): Promise<ProviderGenerateResponse>
  embed(request: ProviderEmbedRequest): Promise<ProviderEmbeddingResponse>
  streamChat(request: ProviderChatRequest, onTokens?: TokenBatchCallback | undefined | null): Promise<ProviderStreamResult>
}

export interface BackendDevice {
  id?: string
  name: string
  type: string
  memoryTotalBytes?: number
  memoryFreeBytes?: number
}

export interface BackendInfo {
  selected: string
  available: Array<string>
  devices: Array<BackendDevice>
}

export declare function backendObservabilityJson(includeDetails?: boolean | undefined | null): string

export interface BackendSelection {
  requested: string
  selected: string
  available: Array<string>
  gpuOffloadExpected: boolean
  reason?: string
}

export interface CacheRuntimeConfig {
  mode?: string
  retained_prefix_tokens?: number
  snapshot_interval_tokens?: number
  max_snapshot_entries?: number
  max_snapshot_bytes?: number
  max_session_entries?: number
  cache_key_policy?: string
  enable_context_checkpoints?: boolean
  checkpoint_every_tokens?: number
}

export interface ChatMessage {
  role: string
  content: string
}

export interface ContextRuntimeConfig {
  n_ctx?: number
  n_batch?: number
  n_ubatch?: number
  n_parallel?: number
  n_threads?: number
  n_threads_batch?: number
  flash_attention?: string
  kv_unified?: boolean
  cache_type_k?: string
  cache_type_v?: string
  offload_kqv?: boolean
  op_offload?: boolean
  swa_full?: boolean
  warmup?: boolean
  rope_scaling?: string
  rope_freq_base?: number
  rope_freq_scale?: number
  yarn_orig_ctx?: number
  yarn_ext_factor?: number
  yarn_attn_factor?: number
  yarn_beta_fast?: number
  yarn_beta_slow?: number
  embeddings?: boolean
  pooling?: PoolingType
}

export interface EmbeddingCapabilities {
  dimensions: number
  pooling: PoolingType
}

export interface EmbeddingResult {
  id: string
  values: Array<number>
  pooling: PoolingType
  normalized: boolean
  stats: RequestStats
}

export interface EmbedOptions {
  normalize?: boolean
  contextKey?: string
}

export interface EmbedRequest {
  input: string
  options?: EmbedOptions
}

export interface EngineEvent {
  type: string
  state?: EngineState
  loadedBytes?: number
  totalBytes?: number
  assetName?: string
  requestId?: string
  streamId?: number
  error?: string
}

export interface EngineState {
  status: string
  model?: ModelState
  backend: BackendInfo
  runtime?: ResolvedRuntimeLimits
  requests: Array<RequestState>
  stats: EngineStats
  updatedAtUnixMs: number
}

export interface EngineStats {
  requestsRunning: number
  requestsQueued: number
  requestsCompleted: number
  requestsFailed: number
  inputTokens: number
  outputTokens: number
  cacheHits: number
  prefillTokens: number
  ttftMs?: number
  interTokenMs?: number
  e2EMs?: number
  tokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
  backendMs: number
  syncMs: number
  engineOverheadMs: number
  debugMetricsSchedulerTicks: number
  debugMetricsDecodeTicks: number
  debugMetricsPrefillTicks: number
  debugMetricsBackendSamplerAttachAttempts: number
  debugMetricsBackendSamplerAttachFailures: number
  debugMetricsAdmitMs: number
  debugMetricsNormalizeMs: number
  debugMetricsBackendSamplerAttachMs: number
  debugMetricsSelectSlotsMs: number
  debugMetricsPlanMs: number
  debugMetricsBatchBuildMs: number
  debugMetricsLlamaDecodeMs: number
  debugMetricsLlamaSyncMs: number
  debugMetricsApplyBookkeepingMs: number
  debugMetricsApplyDecodeResultsMs: number
  debugMetricsSampleMs: number
  debugMetricsTokenPieceMs: number
  debugMetricsEmitMs: number
  debugMetricsPrefixQueueMs: number
  debugMetricsFinalizeMs: number
  debugMetricsCommitObservabilityMs: number
  debugMetricsPostDecodeMs: number
}

export interface GenerationResult {
  id: string
  text: string
  finishReason: string
  stats: RequestStats
}

export interface GpuLayerCountConfig {
  count: number
}

export interface LoadedModelInfo {
  model: ManagedModelInfo
  backend: BackendSelection
  runtimeFingerprint: string
}

export interface LogitBiasConfig {
  token: number
  bias: number
}

export interface ManagedModelInfo {
  id: string
  name: string
  modality: string
  status: string
  source: string
  bytes: number
  loaded: boolean
  chatTemplate?: string
  bosText: string
  eosText: string
  mediaMarker?: string
  createdAtUnixMs: number
  updatedAtUnixMs: number
}

export interface ModelCapabilities {
  modelClass: ModelClass
  supportsTextGeneration: boolean
  supportsEmbeddings: boolean
  hasChatTemplate: boolean
  embedding?: EmbeddingCapabilities
}

export declare const enum ModelClass {
  DecoderOnly = 'decoder_only',
  EncoderDecoder = 'encoder_decoder',
  EncoderOnly = 'encoder_only'
}

export interface ModelLoadOptions {
  backend?: string
  stats?: string
  runtime?: NativeRuntimeConfig
}

export interface ModelPlacementConfig {
  devices?: Array<string>
  gpu_layers?: string | GpuLayerCountConfig
  split_mode?: string
  main_gpu?: number
  tensor_split?: Array<number>
  use_mmap?: boolean
  use_mlock?: boolean
  fit_params?: boolean
  fit_params_min_ctx?: number
  fit_params_target_bytes?: Array<number>
  check_tensors?: boolean
  no_extra_bufts?: boolean
  no_host?: boolean
}

export interface ModelServiceState {
  status: string
  model?: ManagedModelInfo
  backend: BackendInfo
  runtime?: ResolvedRuntimeLimits
  requests: Array<RequestState>
  stats: EngineStats
  updatedAtUnixMs: number
}

export interface ModelState {
  id: string
  name: string
  capabilities: ModelCapabilities
}

export interface MultimodalRuntimeConfig {
  projector_path?: string
  use_gpu?: boolean
  image_min_tokens?: number
  image_max_tokens?: number
}

export interface NativeRuntimeConfig {
  placement?: ModelPlacementConfig
  context?: ContextRuntimeConfig
  sampling?: SamplingRuntimeConfig
  scheduler?: SchedulerRuntimeConfig
  cache?: CacheRuntimeConfig
  multimodal?: MultimodalRuntimeConfig
  residency?: ResidencyRuntimeConfig
  observability?: ObservabilityRuntimeConfig
}

export interface ObservabilityRuntimeConfig {
  runtime_metrics?: boolean
  backend_profiling?: boolean
}

export declare const enum PoolingType {
  Unspecified = 'unspecified',
  None = 'none',
  Mean = 'mean',
  Cls = 'cls',
  Last = 'last',
  Rank = 'rank'
}

export interface ProviderAnthropicConfig {
  apiKey: string
  baseUrl?: string
  version?: string
  timeoutMs?: number
}

export interface ProviderAuthConfig {
  bearer?: string
  header?: ProviderAuthHeaderConfig
}

export interface ProviderAuthHeaderConfig {
  name: string
  value: string
}

export declare const enum ProviderCapabilitySupport {
  Supported = 'supported',
  Unsupported = 'unsupported',
  Unknown = 'unknown'
}

export interface ProviderChatRequest {
  model: string
  messages: Array<ChatMessage>
  options?: ProviderGenerationOptions
  providerOptions?: any
}

export interface ProviderChatResponse {
  result: ProviderTextOutput
  usage?: ProviderTokenUsage
  metadata: ProviderResponseMetadata
}

export interface ProviderEmbeddingOutput {
  values: Array<number>
}

export interface ProviderEmbeddingResponse {
  result: ProviderEmbeddingOutput
  usage?: ProviderTokenUsage
  metadata: ProviderResponseMetadata
}

export interface ProviderEmbedRequest {
  model: string
  input: string
  providerOptions?: any
}

export interface ProviderGenerateRequest {
  model: string
  prompt: string
  options?: ProviderGenerationOptions
  providerOptions?: any
}

export interface ProviderGenerateResponse {
  result: ProviderTextOutput
  usage?: ProviderTokenUsage
  metadata: ProviderResponseMetadata
}

export interface ProviderGenerationOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  stop?: Array<string>
}

export interface ProviderModel {
  id: string
  provider: string
  displayName?: string
  capabilities: ProviderModelCapabilities
  contextWindow?: number
  maxOutputTokens?: number
  raw: any
}

export interface ProviderModelCapabilities {
  chat: ProviderCapabilitySupport
  generate: ProviderCapabilitySupport
  embeddings: ProviderCapabilitySupport
  streaming: ProviderCapabilitySupport
}

export interface ProviderOpenAiConfig {
  apiKey: string
  baseUrl?: string
  timeoutMs?: number
}

export interface ProviderProxyConfig {
  baseUrl: string
  auth: ProviderAuthConfig
  protocol?: ProviderProxyProtocol
  staticHeaders?: Array<ProviderStaticHeaderConfig>
  timeoutMs?: number
}

export declare const enum ProviderProxyProtocol {
  OpenAiCompatible = 'open_ai_compatible'
}

export interface ProviderResponseMetadata {
  provider: string
  model: string
  requestId?: string
  responseId?: string
  finishReasonRaw?: string
  raw: any
}

export interface ProviderStaticHeaderConfig {
  name: string
  value: string
}

export interface ProviderStreamResult {
  usage?: ProviderTokenUsage
  finishReason?: string
}

export interface ProviderTextOutput {
  text: string
  finishReason: string
}

export interface ProviderTokenUsage {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
}

export interface QueryOptions {
  contextKey?: string
  maxTokens?: number
  grammar?: string
  jsonSchema?: string
  stop?: Array<string>
  sampling?: SamplingRuntimeConfig
  media?: Array<Buffer>
}

export interface RequestState {
  id: string
  status: string
  inputTokens: number
  outputTokens: number
}

export interface RequestStats {
  inputTokens: number
  outputTokens: number
  cacheHits: number
  ttftMs?: number
  interTokenMs?: number
  e2EMs?: number
  tokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
  debugMetricsSchedulerTicks: number
  debugMetricsDecodeTicks: number
  debugMetricsPrefillTicks: number
  debugMetricsBackendSamplerAttachAttempts: number
  debugMetricsBackendSamplerAttachFailures: number
  debugMetricsAdmitMs: number
  debugMetricsNormalizeMs: number
  debugMetricsBackendSamplerAttachMs: number
  debugMetricsSelectSlotsMs: number
  debugMetricsPlanMs: number
  debugMetricsBatchBuildMs: number
  debugMetricsLlamaDecodeMs: number
  debugMetricsLlamaSyncMs: number
  debugMetricsApplyBookkeepingMs: number
  debugMetricsApplyDecodeResultsMs: number
  debugMetricsSampleMs: number
  debugMetricsTokenPieceMs: number
  debugMetricsEmitMs: number
  debugMetricsPrefixQueueMs: number
  debugMetricsFinalizeMs: number
  debugMetricsCommitObservabilityMs: number
  debugMetricsPostDecodeMs: number
}

export interface ResidencyRuntimeConfig {
  max_gpu_models_per_device?: number
  allow_cpu_models_while_gpu_loaded?: boolean
  require_gpu_lease?: boolean
  gpu_memory_safety_margin_bytes?: number
}

export interface ResolvedRuntimeLimits {
  nCtx: number
  nBatch: number
  nUbatch: number
  nParallel: number
  kvUnified: boolean
  flashAttention: string
  cacheTypeK: string
  cacheTypeV: string
}

export interface SamplingRuntimeConfig {
  samplers?: Array<string>
  seed?: number
  top_k?: number
  top_p?: number
  min_p?: number
  typical_p?: number
  xtc_probability?: number
  xtc_threshold?: number
  top_n_sigma?: number
  temperature?: number
  dynatemp_range?: number
  dynatemp_exponent?: number
  repeat_last_n?: number
  repeat_penalty?: number
  frequency_penalty?: number
  presence_penalty?: number
  dry_multiplier?: number
  dry_base?: number
  dry_allowed_length?: number
  dry_penalty_last_n?: number
  dry_sequence_breakers?: Array<string>
  mirostat?: number
  mirostat_tau?: number
  mirostat_eta?: number
  min_keep?: number
  n_probs?: number
  logit_bias?: Array<LogitBiasConfig>
  ignore_eos?: boolean
  grammar_lazy?: boolean
  preserved_tokens?: Array<number>
  backend_sampling?: boolean
}

export interface SchedulerPolicyConfig {
  mode?: string
  decode_token_reserve?: number
  enable_adaptive_prefill_chunking?: boolean
}

export interface SchedulerRuntimeConfig {
  continuous_batching?: boolean
  policy?: SchedulerPolicyConfig
  prefill_chunk_size?: number
  max_running_requests?: number
  max_queued_requests?: number
}

export declare function setLlamaLogQuiet(quiet: boolean): void

export interface StreamStats {
  framesSent: number
  bytesSent: number
  framesDropped: number
  batchesSent: number
}

export interface TokenBatch {
  requestId: string
  streamId: number
  sequenceStart: number
  text: string
  frameCount: number
  byteCount: number
  stats: StreamStats
}
