/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CogentClient {
  constructor()
  addLocal(id: string, modelPath: string, config?: NativeRuntimeConfig | undefined | null): Promise<EndpointRef>
  addRemote(id: string, config: RemoteConfig): EndpointRef
  query(request: CogentQueryRequest): CogentTextRun
  chat(request: CogentChatRequest): CogentTextRun
  embed(request: CogentEmbedRequest): CogentEmbeddingRun
}

export declare class CogentTextRun {
  readonly response: Promise<CogentTextResponse>
  readonly tokens: AsyncIterable<TokenBatch>
  [Symbol.asyncIterator](): AsyncIterator<TokenBatch>
}

export declare class CogentEmbeddingRun {
  readonly response: Promise<CogentEmbeddingResponse>
}

export declare function backendObservabilityJson(includeDetails?: boolean | undefined | null): string

export interface CacheRuntimeConfig {
  mode?: string
  retained_prefix_tokens?: number
  snapshot_interval_tokens?: number
  max_snapshot_entries?: number
  max_snapshot_bytes?: number
}

export interface ChatMessage {
  role: string
  content: string
}

export type EndpointRef =
  | {
      kind: 'local'
      id: string
    }
  | {
      kind: 'remote'
      id: string
    }

export interface CogentTextOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  stop?: Array<string>
}

export interface LocalTextOptions {
  contextKey?: string
  grammar?: string
  jsonSchema?: string
  sampling?: SamplingRuntimeConfig
  media?: Array<Buffer>
}

export interface LocalEmbedOptions {
  contextKey?: string
  normalize?: boolean
}

export interface CogentQueryRequest {
  endpoint?: EndpointRef
  prompt: string
  options?: CogentTextOptions
  local?: LocalTextOptions
  remoteOptions?: Record<string, unknown>
  emitTokens?: boolean
}

export interface CogentChatRequest {
  endpoint?: EndpointRef
  messages: Array<ChatMessage>
  options?: CogentTextOptions
  local?: LocalTextOptions
  remoteOptions?: Record<string, unknown>
  emitTokens?: boolean
}

export interface CogentEmbedRequest {
  endpoint?: EndpointRef
  input: string
  local?: LocalEmbedOptions
  remoteOptions?: Record<string, unknown>
}

export interface TokenUsage {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
}

export interface CogentTextResponse {
  endpoint: EndpointRef
  text: string
  finishReason: string
  usage?: TokenUsage
  localStats?: RequestStats
}

export interface CogentEmbeddingResponse {
  endpoint: EndpointRef
  values: Array<number>
  usage?: TokenUsage
  localStats?: RequestStats
  pooling?: PoolingType
  normalized?: boolean
}

export interface ContextRuntimeConfig {
  n_ctx?: number
  n_batch?: number
  n_ubatch?: number
  n_parallel?: number
  n_threads?: number
  n_threads_batch?: number
  flash_attention?: string
  kv_unified?: boolean
  cache_type_k?: string
  cache_type_v?: string
  offload_kqv?: boolean
  op_offload?: boolean
  swa_full?: boolean
  warmup?: boolean
  rope_scaling?: string
  rope_freq_base?: number
  rope_freq_scale?: number
  yarn_orig_ctx?: number
  yarn_ext_factor?: number
  yarn_attn_factor?: number
  yarn_beta_fast?: number
  yarn_beta_slow?: number
  embeddings?: boolean
  pooling?: PoolingType
}

export interface GpuLayerCountConfig {
  count: number
}

export interface LogitBiasConfig {
  token: number
  bias: number
}

export interface ModelPlacementConfig {
  devices?: Array<string>
  gpu_layers?: string | GpuLayerCountConfig
  split_mode?: string
  main_gpu?: number
  tensor_split?: Array<number>
  use_mmap?: boolean
  use_mlock?: boolean
  fit_params?: boolean
  fit_params_min_ctx?: number
  fit_params_target_bytes?: Array<number>
  check_tensors?: boolean
  no_extra_bufts?: boolean
  no_host?: boolean
}

export interface MultimodalRuntimeConfig {
  projector_path?: string
  use_gpu?: boolean
  image_min_tokens?: number
  image_max_tokens?: number
}

export interface NativeRuntimeConfig {
  placement?: ModelPlacementConfig
  context?: ContextRuntimeConfig
  sampling?: SamplingRuntimeConfig
  scheduler?: SchedulerRuntimeConfig
  cache?: CacheRuntimeConfig
  multimodal?: MultimodalRuntimeConfig
  residency?: ResidencyRuntimeConfig
  observability?: ObservabilityRuntimeConfig
}

export interface ObservabilityRuntimeConfig {
  runtime_metrics?: boolean
  backend_profiling?: boolean
}

export declare const enum PoolingType {
  Unspecified = 'unspecified',
  None = 'none',
  Mean = 'mean',
  Cls = 'cls',
  Last = 'last',
  Rank = 'rank'
}

export interface RemoteAuthConfig {
  bearer?: string
  header?: RemoteAuthHeaderConfig
}

export interface RemoteAuthHeaderConfig {
  name: string
  value: string
}

export interface RemoteConfig {
  kind: 'openai' | 'anthropic' | 'proxy'
  model: string
  apiKey?: string
  baseUrl?: string
  version?: string
  auth?: RemoteAuthConfig
  protocol?: RemoteProxyProtocol
  staticHeaders?: Array<RemoteStaticHeaderConfig>
  timeoutMs?: number
}

export declare const enum RemoteProxyProtocol {
  OpenAiCompatible = 'open_ai_compatible'
}

export interface RemoteStaticHeaderConfig {
  name: string
  value: string
}

export interface RequestStats {
  inputTokens: number
  outputTokens: number
  cacheMode: string
  cacheSource: string
  cacheHits: number
  prefillTokens: number
  ttftMs?: number
  interTokenMs?: number
  e2eMs?: number
  e2eTokensPerSecond?: number
  decodeTokensPerSecond?: number
  prefillTokensPerSecond?: number
  prefillMs: number
  decodeMs: number
}

export interface ResidencyRuntimeConfig {
  max_gpu_models_per_device?: number
  allow_cpu_models_while_gpu_loaded?: boolean
  require_gpu_lease?: boolean
  gpu_memory_safety_margin_bytes?: number
}

export interface SamplingRuntimeConfig {
  samplers?: Array<string>
  seed?: number
  top_k?: number
  top_p?: number
  min_p?: number
  typical_p?: number
  xtc_probability?: number
  xtc_threshold?: number
  top_n_sigma?: number
  temperature?: number
  dynatemp_range?: number
  dynatemp_exponent?: number
  repeat_last_n?: number
  repeat_penalty?: number
  frequency_penalty?: number
  presence_penalty?: number
  dry_multiplier?: number
  dry_base?: number
  dry_allowed_length?: number
  dry_penalty_last_n?: number
  dry_sequence_breakers?: Array<string>
  mirostat?: number
  mirostat_tau?: number
  mirostat_eta?: number
  min_keep?: number
  n_probs?: number
  logit_bias?: Array<LogitBiasConfig>
  ignore_eos?: boolean
  grammar_lazy?: boolean
  preserved_tokens?: Array<number>
  backend_sampling?: boolean
}

export interface SchedulerPolicyConfig {
  mode?: string
  decode_token_reserve?: number
  enable_adaptive_prefill_chunking?: boolean
}

export interface SchedulerRuntimeConfig {
  continuous_batching?: boolean
  policy?: SchedulerPolicyConfig
  prefill_chunk_size?: number
  max_running_requests?: number
  max_queued_requests?: number
}

export declare function setLlamaLogQuiet(quiet: boolean): void

export interface TokenEmissionStats {
  framesSent: number
  bytesSent: number
  batchesSent: number
}

export interface TokenBatch {
  requestId: string
  streamId: number
  sequenceStart: number
  text: string
  frameCount: number
  byteCount: number
  stats: TokenEmissionStats
}
